name: "🌟 Roadmap Item"
labels: "Type:Roadmapitem"
description: "How does it create added value?"
title:
  attributes:
    placeholder: "Describe the value that should be created, not the feature"
projects: "opencloud-eu/2"
body:
  - type: textarea
    id: roadmap-description
    attributes:
      label: "Description"
      description: "Describe how this adds value"
      value: |
        Userstory
        As a ..., I want to ... so that ... (stick to whom, what, why)
        Acceptance criteria
    validations:
      required: false
