name: "📦 Roadmap Item"
labels: "Type:Roadmapitem"
description: "Highlevel item users love and actively thank us for"
title: "[name] Value that should be created (not the feature)"
projects: "opencloud-eu/2"
body:
  - type: textarea
    id: roadmap-description
    attributes:
      label: "Description"
      description: "Describe how this adds value"
      value: |
        # Value
        - Value 1
        - Value 2
        - Value 3
    validations:
      required: false
